ifdef::revealjs_slideshow[]

[#cover,data-background-image="image/1156524-bg_redhat.png" data-background-color="#cc0000"]
== &nbsp;

[#cover-h1]
Red Hat^(R)^ Ansible Automation Platform 2

[#cover-h2]
Building Playbook

[#cover-logo]
image::{revealjs_cover_image}[]

endif::[]


== Module Topics
:linkattrs:
* Ansible Distributed Artifacts
* Re-usable playbooks
* Re-usable files and roles
* Re-usable tasks as handlers
* Ansible Roles
* Ansible Collections


== Ansible Distributed Artifacts
.Overview
* One very large playbook
* Break large playbook into distributed and re-usable artifacts:
. Re-usable playbooks
. Re-usable files and roles
. Re-usable tasks as handlers


ifdef::showscript[]

* You can write a simple playbook in one very large file, and most users learn the one-file approach first. However, breaking tasks up into different files is an excellent way to organize complex sets of tasks and reuse them. Smaller, more distributed artifacts let you re-use the same variables, tasks, and plays in multiple playbooks to address different use cases. You can use distributed artifacts across multiple parent playbooks or even multiple times within one playbook. For example, you might want to update your customer database as part of several different playbooks. If you put all the tasks related to updating your database in a tasks file, you can re-use them in many playbooks while only maintaining them in one place.
endif::showscript[]


== Re-usable playbooks
.Incorporates playbooks 
* *import_playbook*
+
[source,sh]
----
$ cat playbook.yml
- import_playbook: webservers.yml <1>
- import_playbook: "{{ playbook_path }}" <2>
  vars:
    playbook_path: /path/to/one_playbook.yml
----

ifdef::showscript[]

* You can incorporate multiple playbooks into a main playbook. However, you can only use imports to re-use playbooks

* You can select which playbook you want to import at runtime by defining your imported playbook filename with a variable, then passing the variable with either --extra-vars or the vars keyword. 
endif::showscript[]


== Re-usable files and roles
.Ansible artifacts
. Variable files
. Task files
. Playbooks
. Roles


ifdef::showscript[]

* Ansible offers four distributed, re-usable artifacts: variables files, task files, playbooks, and roles.
. A variables file contains only variables.
. A task file contains only tasks.
. A playbook contains at least one play, and may contain variables, tasks, and other content. You can re-use tightly focused playbooks, but you can only re-use them statically, not dynamically.
. A role contains a set of related tasks, variables, defaults, handlers, and even modules or other plugins in a defined file-tree. Unlike variables files, task files, or playbooks, roles can be easily uploaded and shared via Ansible Galaxy. See Roles for details about creating and using roles.
endif::showscript[]


== Re-usable files and roles (cont..)
.How to incorporate artifacts
* *_For dynamic re-use:_*
. include_role
. include_tasks
. include_vars
* *_For static re-use:_*
. import_role
. import_tasks

ifdef::showscript[]

* Ansible offers two ways to re-use files and roles in a playbook: dynamic and static.
. For dynamic re-use, add an include_* task in the tasks section of a play:
. For static re-use, add an import_* task in the tasks section of a play:
endif::showscript[]


== Re-usable files and roles (cont..)
.Handlers
* Dynamic trigger
    ** Include handlers with *include_tasks*
* Static trigger 
    ** Import handlers with *import_tasks*

ifdef::showscript[]
* You can also use includes and imports in the Handlers: running operations on change section of a playbook.

* Triggering included (dynamic) handlers:
+
Includes are executed at run-time, so the name of the include exists during play execution, but the included tasks do not exist until the include itself is triggered. To use the tasks with dynamic re-use, refer to the name of the include itself. This approach triggers all tasks in the included file as handlers.

* Triggering imported (static) handlers:
+
Imports are processed before the play begins, so the name of the import no longer exists during play execution, but the names of the individual imported tasks do exist. To use the Restart apache task with static re-use, refer to the name of each task or tasks within the imported file.

endif::showscript[]

== Re-usable files and roles (cont..)
.Include vs Import

* *Includes:* dynamic re-use
** Ansible processes included files and roles as they come up in a playbook.
* *Imports:* static re-use
** Ansible pre-processes imported files and roles before it runs any tasks in a playbook.

ifdef::showscript[]

* Includes: dynamic re-use - Including roles, tasks, or variables adds them to a playbook dynamically. Ansible processes included files and roles as they come up in a playbook, so included tasks can be affected by the results of earlier tasks within the top-level playbook. Included roles and tasks are similar to handlers - they may or may not run, depending on the results of other tasks in the top-level playbook.

 The primary advantage of using include_* statements is looping. When a loop is used with an include, the included tasks or role will be executed once for each item in the loop.

* Imports: static re-use - Importing roles, tasks, or playbooks adds them to a playbook statically. Ansible pre-processes imported files and roles before it runs any tasks in a playbook, so imported content is never affected by other tasks within the top-level playbook.
endif::showscript[]

// == Re-usable files and roles (cont..)
// .Include vs Import
// [%autowidth,cols="^.^,a,a,a",options="header"]
// |===
// |SR No | Use | Include_* | Import_*
// |{counter:start_file}| Type of re-use | Dynamic |Static
// |{counter:start_file}| When processed | At runtime, when encountered | Pre-processed during playbook parsing
// |{counter:start_file}| Task or play	| All includes are tasks | import_playbook cannot be a task
// |{counter:start_file}| Task options	| Apply only to include task itself | Apply to all child tasks in import
// |{counter:start_file}| Calling from loops | Executed once for each loop item | Cannot be used in a loop
// |{counter:start_file}| Using --list-tags	| Tags within includes not listed | All tags appear with --list-tags
// |===

// == Re-usable files and roles (cont..)
// .Include vs Import (continue...)
// [%autowidth,cols="^.^,a,a,a",options="header"]
// |===
// |SR No| Use | Include_* | Import_*
// |{counter:start_file}| Using --list-tasks | Tasks within includes not listed | All tasks appear with --list-tasks
// |{counter:start_file}| Notifying handlers | Cannot trigger handlers within includes | Can trigger individual imported handlers
// |{counter:start_file}| Using --start-at-task	 | Cannot start at tasks within includes | Can start at imported tasks
// |{counter:start_file}| Using inventory variables	 | Can include_*: {{ inventory_var }} | Cannot import_*: {{ inventory_var }}
// |{counter:start_file}| With playbooks | No include_playbook |Can import full playbooks
// |{counter:start_file}| With variables files | Can include variables files | Use vars_files: to import variables
// |===


== Ansible Roles
.Roles - Good Practice
* Keep roles purpose and function-focused 
* Limit role dependencies
* Use *roles* subdirectory for roles development
* Follow Ansible Galaxy pattern
* Use *ansible-galaxy init* to start roles


== Ansible Roles (cont..)
.Roles - Installation
* Use *ansible-galaxy* to install roles
* Use roles files (i.e., *requirements.yml*) to manifest roles
+
.Sample Requirements.yml
[source,sh]
----
- src: yatesr.timezone <1>

- src: https://github.com/bennojoy/nginx <2>
  version: v1.4

- src: https://some.webserver.example.com/files/master.tar.gz <3>
  name: http-role
----

 

== Ansible Collections
.Overview
* New, and still evolving packaging and distribution of Ansible:
** modules
** plugins
** roles
** playbooks
* Allows stronger association between roles, modules and plugins



== Ansible Collections (cont..)
.Create Collection
* Use *ansible-galaxy* to creating collection skeleton
+
.Sample command line
[source,sh]
----
$ ansible-galaxy collection init gpte.ansible_training \
  --init-path ./collections/ansible_collections <1>
----
+
.Sample Structure
[source,textinfo]
----
collections <1>
└── ansible_collections <2>
    └── gpte <3>
        └── ansible_training <4>
            ├── README.md
            ├── docs
            ├── galaxy.yml
            ├── playbooks <5>
            ├── plugins <6>
            │   └── README.md
            └── roles <7>
----

ifdef::showscript[]

NOTE: Some optional sub directories not yet in use in `2.9`
Resources:
* link:https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#developing-collections[Developing Collections$

endif::showscript[]



== Ansible Collections (cont..)
.Installation from Ansible Galaxy
* Uses Ansible Galaxy as primary distribution method
* Collection uses namespacing:
** Ex: *openstack.cloud* - openstack is namespace and cloud is collection
* *_Sample Commands & Options_*
+
[source,sh]
----
$ ansible-galaxy collection install awx.awx <1>
$ ansible-galaxy collection install -r collections/requirements.yml -p collections <2>
----
* *_Sample Collection Requirements.yml_*
+
[source,yaml]
----
collections: <1>
  - name: awx.awx <2>
    version: "11.2.0" <3>
----


== Ansible Collections (cont..)
.Installation from Automation Hub
* Configure a Galaxy server list in *ansible.cfg* to use other servers 
** such as Red Hat Automation Hub or a custom Galaxy server
* *_Sample configuration options_*
+
[source,textinfo]
----
[galaxy] <1>
server_list = automation_hub, my_org_hub <2>

[galaxy_server.automation_hub] <3>
url=https://cloud.redhat.com/api/automation-hub/ <4>
auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token <5>
token=my_ah_token <5>

[galaxy_server.my_org_hub] <7>
url=https://automation.my_org/ 
username=my_user
password=my_pass
----




== Ansible Collections (cont..)
.Using Collections
* There are two ways to call a collection component (role, module etc)
** *FQCN* (Fully Qualified Collection Name), format: *<organization_namespace>.<collection>.<module_name>*
+
[source,yaml]
----
  tasks:
    - name: Create GPTE Organization
      awx.awx.tower_organization: <1>
        name: GPTE 
        description: GPTE Organization 
        state: present
----

** *collections* keyword supporting a precedence list
+
[source,yaml]
----
  hosts: localhost
  collections: <1>
    - awx.awx <2>
    - gpte.tower_utilities <3>
  tasks:
    - name: Create GPTE Organization
      tower_organization: <4>
        name: GPTE 
        description: GPTE Organization 
        state: present
----

== Summary
* Ansible Distributed Artifacts
* Re-usable playbooks
* Re-usable files and roles
* Re-usable tasks as handlers
* Ansible Roles
* Ansible Collections